title: Eléments biens connus utilisés pour définir des cartes LLMap
$schema:
  $id: https://igngp.geoapi.fr/llmap.yaml#/schema
  type: object
  additionalProperties: false
  properties:
    title:
      type: string
    $schema:
      description: schéma de ce document
      $ref: http://json-schema.org/schema#
    plugIns:
      description: Dict. des plug-ins biens connus
      type: object
      additionalProperties: false
      patternProperties:
        ^[-a-zA-Z0-9.]+$:
          type: object
          additionalProperties: false
          properties:
            title:
              description: titre du plug-in
              type: string
            source:
              description: URL du plug-in
              type: string
            include:
              description: code d'inclusion du plug-in à inclure dans l'en-tête du fichier Html
              type: string
            activation:
              description: code JS d'activation du plug-in
              type: string
    layers:
      description: Dictionnaire des couches biens connues
      $ref: /var/www/html/geoapi/igngp/llmap.schema.yaml#/definitions/lyrDict
    views:
      description: Dictionnaire de vues bien connues
      type: object
      additionalProperties: false
      patternProperties:
        ^[-a-zA-Z0-9.]+$:
          type: object
          additionalProperties: false
          required: [latLon, zoom]
          properties:
            latLon:
              type: array
              maxItems: 2
              minItems: 2
              items:
                type: number
            zoom:
              type: integer
    eof:
      type: 'null'
plugIns:
  Control.Coordinates:
    title: Leaflet.Coordinates -  A Leaflet plugin to view mouse coordinates
    source: https://github.com/MrMufflon/Leaflet.Coordinates
    include: |
      <!-- Include the Control.Coordinates plugin -->
      <link rel='stylesheet' href='https://geoapi.fr/shomgt/leaflet/Control.Coordinates.css'>
      <script src='https://geoapi.fr/shomgt/leaflet/Control.Coordinates.js'></script>
    activation: |
      // activation du plug-in Control.Coordinates
      var c = new L.Control.Coordinates();
      c.addTo(map);
      map.on('click', function(e) { c.setCoordinates(e); });
  edgebuffer:
    title: Leaflet.EdgeBuffer - Leaflet 1.0 plugin to support pre-loading tiles outside the current viewport on L.GridLayer-based layers
    source: https://github.com/TolonUK/Leaflet.EdgeBuffer
    include: |
      <!-- Include the edgebuffer plugin -->
      <script src="https://geoapi.fr/shomgt/leaflet/leaflet.edgebuffer.js"></script>
  leaflet-ajax:
    title: leaflet-ajax - Allows you to call JSON via an Ajax call with a jsonp fallback
    source: https://github.com/calvinmetcalf/leaflet-ajax
    include: |
      <!-- plug-in d'appel des GeoJSON en AJAX -->
      <script src='https://geoapi.fr/shomgt/leaflet/leaflet-ajax.js'></script>
  uGeoJSON:
    title: Leaflet uGeoJSON Layer - A Leaflet plugin to create a custom GeoJSON overlay which is updated after each drag and each zoom
    source: https://github.com/BenjaminVadant/leaflet-ugeojson
    include: |
      <!-- Include the uGeoJSON plugin -->
      <script src="https://geoapi.fr/shomgt/leaflet/leaflet.uGeoJSON.js"></script>
layers:
  plan-ignv2:
    type: L.TileLayer
    params:
      - 'https://igngp.geoapi.fr/tile.php/plan-ignv2/{z}/{x}/{y}.png'
      - format: image/png
        minZoom: 0
        maxZoom: 18
        detectRetina: false
        attribution: "&copy; <a href='http://www.ign.fr' target='_blank'>IGN</a>"
  OSM:
    type: L.TileLayer
    params:
      - 'http://{s}.tile.osm.org/{z}/{x}/{y}.png'
      - attribution: "&copy; <a href='https://www.openstreetmap.org/copyright' target='_blank'>les contributeurs d’OpenStreetMap</a>"
  fondBlanc:
    type: L.TileLayer
    params:
      - 'https://visu.gexplor.fr/utilityserver.php/whiteimg/{z}/{x}/{y}.jpg'
      - format: image/jpeg
        minZoom: 0
        maxZoom: 21
        detectRetina: false
  debug:
    type: L.TileLayer
    params:
      - 'http://visu.gexplor.fr/utilityserver.php/debug/{z}/{x}/{y}.png'
      - {"format": "image/png","minZoom": 0,"maxZoom": 21,"detectRetina": false}
views:
  metropole:
    latLon: [46.5, 3]
    zoom: 6
eof:
